#!/usr/bin/env python3
"""Write construct seq files + BoltzFT-schema results CSVs for the 7 non-588689 targets.

Sequences: 5 from reference PDBs (Boltzina Table 1), 2 predicted-holo targets from NCBI GI.
Cross-checked via PubChem: 493248->ALR==3MBG, 588689->NS5==3EVG.
"""
from pathlib import Path
import pandas as pd

ROOT = Path("/global/scratch/users/sergiomar10/boltzaff")
DATA = ROOT / "data"

SEQS = {
 # target-folder : (source, sequence)
 "1053173-743445": ("6UE6/NSD2-PWWP1",
  "GGRDKDHLLKYNVGDLVWSKVSGYPWWPCMVSADPLLHSYTKLKGQKKSARQYHVQFFGDAPERAWIFEKSLVAFEGEGQFEKLCQESAKQAPTKAEKIKLLKPISGKLRAQWEMGIVQAEEAASMSVEERKAKFTFLYVG"),
 "493248-485317": ("3MBG/ALR-GFER",
  "MGGSHHHHHHGMASMRTQQKRDTKFREDCPPDREELGRHSWAVLHTLAAYYPDLPTPEQQQDMAQFIHLFSKFYPCEECAEDLRKRLARNHPDTRTRAAFTQWLCHLHNEVNRKLGKPDFDCSKVDERWRDGWKDGSCD"),
 "434954-2097": ("1J1B/GSK3B",
  "MSGRPRTTSFAESCKPVQQPSAFGSMKVSRDKDGSKVTTVVATPGQGPDRPQEVSYTDTKVIGNGSFGVVYQAKLCDSGELVAIKKVLQDKRFKNRELQIMRKLDHCNIVRLRYFFYSSGEKKDEVYLNLVLDYVPETVYRVARHYSRAKQTLPVIYVKLYMYQLFRSLAYIHSFGICHRDIKPQNLLLDPDTAVLKLCDFGSAKQLVRGEPNVSYICSRYYRAPELIFGATDYTSSIDVWSAGCVLAELLLGQPIFPGDSGVDQLVEIIKVLGTPTREQIREMNPNYTEFKFPQIKAHPWTKVFRPRTPPEAIALCSRLLEYTPTARLTPLEACAHSFFDELRDPNVKLPNGRDTPALFNFTTQELSSNPPLATILIPPHARIQAAASTPTNATAASDANTGDRGQTNNAASASASNST"),
 "540297-493091": ("3PGL/SCP1",
  "QYLLPEAKAQDSDKICVVIDLDETLVHSSFKPVNNADFIIPVEIDGVVHQVYVLKRPHVDEFLQRMGELFECVLFTASLAKYADPVADLLDKWGAFRARLFRESCVFHRGNYVKDLSRLGRDLRRVLILDNSPASYVFHPDNAVPVASWFDNMSDTELHDLLPFFEQLSRVDDVYSVLRQ"),
 "463203-2650": ("7SXF/GSK3A",
  "TTVVATLGQGPERSQEVAYTDIKVIGNGSFGVVYQARLAETRELVAIKKVLQDKRFKNRELQIMRKLDHCNIVRLRYFFYSSGEKKDELYLNLVLEYVPETVYRVARHFTKAKLTIPILYVKVYMYQLFRSLAYIHSQGVCHRDIKPQNLLVDPDTAVLKLCDFGSAKQLVRGEPNVSYICSRYYRAPELIFGATDYTSSIDVWSAGCVLAELLLGQPIFPGDSGVDQLVEIIKVLGTPTREQIREMNPNYTEFKFPQIKAHPWTKVFKSRTPPEAIALCSSLLEYTPSSRLSPLEACAHSFFDELRCLGTQLPNNRPLPPLFNFSAGELSIQPSLNAILIPPHR"),
 "504329": ("NS1/InfluenzaA-H1N1(GI227977143)",
  "MDSNTMSSFQVDCFLWHIRKRFADNGLGDAPFLDRLRRDQKSLKGRGNTLGLDIETATLVGKQIVEWILKEESSETLRMTIASVPTSRYLSDMTLEEMSRDWFMLMPRQKIIGPLCVRLDQAIMEKNIVLKANFSVIFNRLETLILLRAFTEEGAIVGEISPLPSLPGHTYEDVKNAVGVLIGGLEWNGNTVRVSENIQRFAWRNCDENGRPSLPPEQK"),
 "624273-588549": ("FadD28/Mtb(GI1781172)",
  "MSVRSLPAALRACARLQPHDPAFTFMDYEQDWDGVAITLTWSQLYRRTLNVAQELSRCGSTGDRVVISAPQGLEYVVAFLGALQAGRIAVPLSVPQGGVTDERSDSVLSDSSPVAILTTSSAVDDVVQHVARRPGESPPSIIEVDLLDLDAPNGYTFKEDEYPSTAYLQYTSGSTRTPAGVVMSHQNVRVNFEQLMSGYFADTDGIPPPNSALVSWLPFYHDMGLVIGICAPILGGYPAVLTSPVSFLQRPARWMHLMASDFHAFSAAPNFAFELAARRTTDDDMAGRDLGNILTILSGSERVQAATIKRFADRFARFNLQERVIRPSYGLAEATVYVATSKPGQPPETVDFDTESLSAGHAKPCAGGGATSLISYMLPRSPIVRIVDSDTCIECPDGTVGEIWVHGDNVANGYWQKPDESERTFGGKIVTPSPGTPEGPWLRTGDSGFVTDGKMFIIGRIKDLLIVYGRNHSPDDIEATIQEITRGRCAAISVPGDRSTEKLVAIIELKKRGDSDQDAMARLGAIKREVTSALSSSHGLSVADLVLVAPGSIPITTSGKVRRGACVEQYRQDQFARLDA"),
}


def main() -> None:
    for tgt, (src, seq) in SEQS.items():
        (DATA / f"{tgt}_seq.txt").write_text(seq + "\n")
        df = pd.read_csv(DATA / "mf-pcba_test" / f"{tgt}.csv")
        out = pd.DataFrame({
            "CID": df["CID"].astype(int),
            "neut-smiles": df["neut-smiles"],
            "Active_v2": df["target_active_v2"].astype(bool).astype(int),
            "affinity_probability_binary": df["score_boltz2"],
        })
        out.to_csv(DATA / f"{tgt}_results.csv", index=False)
        print(f"{tgt:16s} src={src:34s} len={len(seq):4d} rows={len(out):6d} actives={int(out.Active_v2.sum())}")


if __name__ == "__main__":
    main()
